"""
3. WARRANTIES, LIABILITY AND GUARANTEES
IN NO EVENT SHALL FREELANCER BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, 
SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, 
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF BIOCOM 
SOFTWARE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

EXCEPT AS INDICATED IN LEGALLY BINDING WRITINGS THAT SUPERSEDE THIS DISCLAIMER, 
FREELANCER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT 
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE. THE SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, 
PROVIDED HEREUNDER IS PROVIDED "AS IS". FREELANCER HAS NO OBLIGATION TO 
PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

ANY PARTS OF THIS CLAUSE NOT SPECIFICALLY SUPERSEDED REMAIN VALID AND IN PLACE
REGARDLESS OF THE ESIXTENCE OF OTHER WARRRANTY DOCUMENTATION. 
"""